const songs = [
  {
    index: 0,
    name: "In and out of love",
    artist: "Armin van Buuren & Sharon den Adel",
    song: "In and out of love.mp3",
    way: "../songs/",
    album: "Armin van Buuren & Sharon den Adel",
    duration: "05:58",
  },
  {
    index: 1,
    name: "We are under one heaven",
    artist: "Aida Nikolaychuk",
    song: "Aida Nikolaychuk - We are under one heaven.mp3",
    way: "../songs/",
    album: "",
    duration: "03:20",
  },
  {
    index: 2,
    name: "Better when Im dancing",
    artist: "Meghan Trainor",
    song: "m1.mp3",
    way: "../songs/",
    album: "Meghen and Friends",
    duration: "02:56",
  },
  {
    index: 3,
    name: "Levitate",
    artist: "Hadouken!",
    song: "Hadouken! - Levitate.mp3",
    way: "../songs/",
    album: "",
    duration: "04:38",
  },
  {
    index: 4,
    name: "Thousand Miles",
    artist: "Tove Lo",
    song: "Tove Lo - Thousand Miles.mp3",
    way: "../songs/",
    album: "",
    duration: "03:28",
  },
  {
    index: 5,
    name: "The water and the sun",
    artist: "ZEB",
    song: "ZEB - The water and the sun.mp3",
    way: "../songs/",
    album: "",
    duration: "06:15",
  },
  {
    index: 6,
    name: "Crying for no reason",
    artist: "Katy B",
    song: "Katy B - Crying for no reason.mp3",
    way: "../songs/",
    album: "",
    duration: "04:00",
  },
  {
    index: 7,
    name: "Hold me tight",
    artist: "KOSIKK",
    song: "KOSIKK - Hold me tight.mp3",
    way: "../songs/",
    album: "",
    duration: "03:50",
  },
  {
    index: 8,
    name: "Far Centaurus",
    artist: "Nigel Stanford",
    song: "Nigel Stanford - Far Centaurus.mp3",
    way: "../songs/",
    album: "",
    duration: "09:58",
  },

  {
    index: 9,
    name: "Feel",
    artist: "Robbie Williams",
    song: "Robbie Williams - Feel.mp3",
    way: "../songs/",
    album: "",
    duration: "03:39",
  },

  {
    index: 9,
    name: "Intro HQ",
    artist: "The XX",
    song: "The XX - Intro HQ.mp3",
    way: "../songs/",
    album: "",
    duration: "06:49",
  },
];
